//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WpfMath
{
    public partial class CharFont
    {
        public CharFont(char character, int fontId) { }
        public char Character { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public int FontId { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
    }
    public partial class CharInfo
    {
        public CharInfo(char character, WpfMath.Fonts.IFontTypeface font, double size, int fontId, WpfMath.TeXFontMetrics metrics) { }
        public char Character { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.Fonts.IFontTypeface Font { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public int FontId { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public WpfMath.TeXFontMetrics Metrics { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Size { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.CharFont GetCharacterFont() { throw null; }
    }
    public partial class DelimiterMappingNotFoundException : System.Exception
    {
        internal DelimiterMappingNotFoundException() { }
    }
    public partial class ExtensionChar
    {
        public ExtensionChar(WpfMath.CharInfo? top, WpfMath.CharInfo? middle, WpfMath.CharInfo? bottom, WpfMath.CharInfo? repeat) { }
        public WpfMath.CharInfo? Bottom { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public WpfMath.CharInfo? Middle { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public WpfMath.CharInfo? Repeat { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public WpfMath.CharInfo? Top { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
    }
    public partial class FormulaNotFoundException : System.Exception
    {
        internal FormulaNotFoundException() { }
    }
    public enum MatrixCellAlignment
    {
        Left = 0,
        Center = 1,
    }
    public partial class SourceSpan : System.IEquatable<WpfMath.SourceSpan>
    {
        public SourceSpan(string sourceName, string source, int start, int length) { }
        public int End { get { throw null; } }
        public char this[int index] { get { throw null; } }
        public int Length { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public string Source { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public string SourceName { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public int Start { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public override bool Equals(object? obj) { throw null; }
        public bool Equals(WpfMath.SourceSpan? other) { throw null; }
        public override int GetHashCode() { throw null; }
        public WpfMath.SourceSpan Segment(int start) { throw null; }
        public WpfMath.SourceSpan Segment(int start, int length) { throw null; }
        public override string ToString() { throw null; }
    }
    public partial class SymbolMappingNotFoundException : System.Exception
    {
        internal SymbolMappingNotFoundException() { }
    }
    public partial class SymbolNotFoundException : System.Exception
    {
        internal SymbolNotFoundException() { }
    }
    public enum TexAlignment
    {
        Left = 0,
        Right = 1,
        Center = 2,
        Top = 3,
        Bottom = 4,
    }
    public enum TexAtomType
    {
        None = -1,
        Ordinary = 0,
        BigOperator = 1,
        BinaryOperator = 2,
        Relation = 3,
        Opening = 4,
        Closing = 5,
        Punctuation = 6,
        Inner = 7,
        Accent = 10,
    }
    public enum TexDelimeterType
    {
        Over = 0,
        Under = 1,
    }
    public enum TexDelimiter
    {
        Brace = 0,
        Parenthesis = 1,
        Bracket = 2,
        LeftArrow = 3,
        RightArrow = 4,
        LeftRightArrow = 5,
        DoubleLeftArrow = 6,
        DoubleRightArrow = 7,
        DoubleLeftRightArrow = 8,
        SingleLine = 9,
        DoubleLine = 10,
    }
    public sealed partial class TexEnvironment : System.IEquatable<WpfMath.TexEnvironment>
    {
        public TexEnvironment(WpfMath.TexStyle Style, WpfMath.Fonts.ITeXFont MathFont, WpfMath.Fonts.ITeXFont TextFont, WpfMath.Rendering.IBrush? Background = null, WpfMath.Rendering.IBrush? Foreground = null) { }
        public WpfMath.Rendering.IBrush? Background { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.Rendering.IBrush? Foreground { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.Fonts.ITeXFont MathFont { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.TexStyle Style { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.Fonts.ITeXFont TextFont { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Deconstruct(out WpfMath.TexStyle Style, out WpfMath.Fonts.ITeXFont MathFont, out WpfMath.Fonts.ITeXFont TextFont, out WpfMath.Rendering.IBrush? Background, out WpfMath.Rendering.IBrush? Foreground) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override bool Equals(object? obj) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public bool Equals(WpfMath.TexEnvironment? other) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override int GetHashCode() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator ==(WpfMath.TexEnvironment? left, WpfMath.TexEnvironment? right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator !=(WpfMath.TexEnvironment? left, WpfMath.TexEnvironment? right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override string ToString() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public WpfMath.TexEnvironment <Clone>$() { throw null; }
    }
    public partial class TeXFontMetrics
    {
        public TeXFontMetrics(double width, double height, double depth, double italicWidth, double scale) { }
        public double Depth { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Height { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Italic { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Width { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    public sealed partial class TexFormula
    {
        public TexFormula() { }
        public WpfMath.SourceSpan? Source { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public string? TextStyle { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public void Add(WpfMath.TexFormula formula, WpfMath.SourceSpan? source = null) { }
        public void SetBackground(WpfMath.Rendering.IBrush brush) { }
        public void SetForeground(WpfMath.Rendering.IBrush brush) { }
    }
    public partial class TexFormulaParser
    {
        public TexFormulaParser(System.Collections.Generic.IReadOnlyDictionary<string, WpfMath.Colors.IColorParser> colorModelParsers, WpfMath.Colors.IColorParser defaultColorParser, WpfMath.Rendering.IBrushFactory brushFactory, System.Collections.Generic.IReadOnlyDictionary<string, System.Func<WpfMath.SourceSpan, WpfMath.TexFormula?>> predefinedFormulae) { }
        public TexFormulaParser(WpfMath.Rendering.IBrushFactory brushFactory, System.Collections.Generic.IReadOnlyDictionary<string, System.Func<WpfMath.SourceSpan, WpfMath.TexFormula?>> predefinedFormulae) { }
        public WpfMath.TexFormula Parse(string value, string? textStyle = null) { throw null; }
        public WpfMath.TexFormula Parse(WpfMath.SourceSpan value, string? textStyle = null) { throw null; }
    }
    public enum TexStyle
    {
        Display = 0,
        Text = 2,
        Script = 4,
        ScriptScript = 6,
    }
    public enum TexUnit
    {
        Em = 0,
        Ex = 1,
        Pixel = 2,
        Point = 3,
        Pica = 4,
        Mu = 5,
    }
}
namespace WpfMath.Boxes
{
    public abstract partial class Box
    {
        protected Box() { }
        protected Box(WpfMath.Rendering.IBrush? foreground, WpfMath.Rendering.IBrush? background) { }
        public WpfMath.Rendering.IBrush? Background { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public System.Collections.ObjectModel.ReadOnlyCollection<WpfMath.Boxes.Box> Children { get { throw null; } }
        public double Depth { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.Rendering.IBrush? Foreground { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Height { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Italic { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Shift { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.SourceSpan? Source { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double TotalHeight { get { throw null; } }
        public double TotalWidth { get { throw null; } }
        public double Width { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public virtual void Add(int position, WpfMath.Boxes.Box box) { }
        public virtual void Add(WpfMath.Boxes.Box box) { }
        public abstract int GetLastFontId();
        public abstract void RenderTo(WpfMath.Rendering.IElementRenderer renderer, double x, double y);
    }
}
namespace WpfMath.Colors
{
    public abstract partial class FixedComponentCountColorParser : WpfMath.Colors.IColorParser
    {
        protected FixedComponentCountColorParser(int componentCount) { }
        public WpfMath.Colors.RgbaColor? Parse(System.Collections.Generic.IEnumerable<string> components) { throw null; }
        protected abstract WpfMath.Colors.RgbaColor? ParseComponents(System.Collections.Generic.List<string> components);
    }
    public partial interface IColorParser
    {
        WpfMath.Colors.RgbaColor? Parse(System.Collections.Generic.IEnumerable<string> components);
    }
    public partial class PredefinedColorParser : WpfMath.Colors.IColorParser
    {
        internal PredefinedColorParser() { }
        public static readonly WpfMath.Colors.PredefinedColorParser Instance;
        public WpfMath.Colors.RgbaColor? Parse(System.Collections.Generic.IEnumerable<string> components) { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct RgbaColor : System.IEquatable<WpfMath.Colors.RgbaColor>
    {
        private object _dummy;
        private int _dummyPrimitive;
        public RgbaColor(byte R, byte G, byte B, byte A = (byte)255) { throw null; }
        public byte A { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public byte B { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public byte G { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public byte R { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Deconstruct(out byte R, out byte G, out byte B, out byte A) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override bool Equals(object obj) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public bool Equals(WpfMath.Colors.RgbaColor other) { throw null; }
        public static WpfMath.Colors.RgbaColor FromArgb(byte a, byte r, byte g, byte b) { throw null; }
        public static WpfMath.Colors.RgbaColor FromRgb(byte r, byte g, byte b) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override int GetHashCode() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator ==(WpfMath.Colors.RgbaColor left, WpfMath.Colors.RgbaColor right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator !=(WpfMath.Colors.RgbaColor left, WpfMath.Colors.RgbaColor right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override string ToString() { throw null; }
    }
    public static partial class StandardColorParsers
    {
        public static System.Collections.Generic.IReadOnlyDictionary<string, WpfMath.Colors.IColorParser> Dictionary;
    }
}
namespace WpfMath.Exceptions
{
    public partial class TexCharacterMappingNotFoundException : WpfMath.Exceptions.TexException
    {
        public TexCharacterMappingNotFoundException(string message) { }
    }
    public abstract partial class TexException : System.Exception
    {
        public TexException() { }
        public TexException(string message) { }
        public TexException(string message, System.Exception innerException) { }
    }
    public partial class TexNotSupportedException : WpfMath.Exceptions.TexException
    {
        public TexNotSupportedException(string message) { }
    }
    public partial class TexParseException : WpfMath.Exceptions.TexException
    {
        internal TexParseException() { }
    }
    public partial class TextStyleMappingNotFoundException : WpfMath.Exceptions.TexException
    {
        internal TextStyleMappingNotFoundException() { }
    }
    public partial class TypeFaceNotFoundException : WpfMath.Exceptions.TexException
    {
        public TypeFaceNotFoundException(string message) { }
    }
}
namespace WpfMath.Fonts
{
    public partial interface IFontProvider
    {
        WpfMath.Fonts.IFontTypeface ReadFontFile(string fontFileName);
    }
    public partial interface IFontTypeface
    {
    }
    public partial interface ITeXFont
    {
        double Size { get; }
        bool SupportsMetrics { get; }
        double GetAxisHeight(WpfMath.TexStyle style);
        double GetBigOpSpacing1(WpfMath.TexStyle style);
        double GetBigOpSpacing2(WpfMath.TexStyle style);
        double GetBigOpSpacing3(WpfMath.TexStyle style);
        double GetBigOpSpacing4(WpfMath.TexStyle style);
        double GetBigOpSpacing5(WpfMath.TexStyle style);
        WpfMath.Utils.Result<WpfMath.CharInfo> GetCharInfo(char character, string textStyle, WpfMath.TexStyle style);
        WpfMath.Utils.Result<WpfMath.CharInfo> GetCharInfo(string name, WpfMath.TexStyle style);
        WpfMath.Utils.Result<WpfMath.CharInfo> GetCharInfo(WpfMath.CharFont charFont, WpfMath.TexStyle style);
        WpfMath.Utils.Result<WpfMath.CharInfo> GetDefaultCharInfo(char character, WpfMath.TexStyle style);
        double GetDefaultLineThickness(WpfMath.TexStyle style);
        double GetDenom1(WpfMath.TexStyle style);
        double GetDenom2(WpfMath.TexStyle style);
        WpfMath.ExtensionChar GetExtension(WpfMath.CharInfo charInfo, WpfMath.TexStyle style);
        double GetKern(WpfMath.CharFont leftChar, WpfMath.CharFont rightChar, WpfMath.TexStyle style);
        WpfMath.CharFont? GetLigature(WpfMath.CharFont leftChar, WpfMath.CharFont rightChar);
        int GetMuFontId();
        WpfMath.CharInfo GetNextLargerCharInfo(WpfMath.CharInfo charInfo, WpfMath.TexStyle style);
        double GetNum1(WpfMath.TexStyle style);
        double GetNum2(WpfMath.TexStyle style);
        double GetNum3(WpfMath.TexStyle style);
        double GetQuad(int fontId, WpfMath.TexStyle style);
        double GetSkew(WpfMath.CharFont charFont, WpfMath.TexStyle style);
        double GetSpace(WpfMath.TexStyle style);
        double GetSub1(WpfMath.TexStyle style);
        double GetSub2(WpfMath.TexStyle style);
        double GetSubDrop(WpfMath.TexStyle style);
        double GetSup1(WpfMath.TexStyle style);
        double GetSup2(WpfMath.TexStyle style);
        double GetSup3(WpfMath.TexStyle style);
        double GetSupDrop(WpfMath.TexStyle style);
        double GetXHeight(WpfMath.TexStyle style, int fontId);
        bool HasNextLarger(WpfMath.CharInfo charInfo);
        bool HasSpace(int fontId);
        bool IsExtensionChar(WpfMath.CharInfo charInfo);
    }
}
namespace WpfMath.Rendering
{
    public partial class GenericBrush<TBrush> : System.IEquatable<WpfMath.Rendering.GenericBrush<TBrush>>, WpfMath.Rendering.IBrush
    {
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        protected GenericBrush(WpfMath.Rendering.GenericBrush<TBrush> original) { }
        public GenericBrush(TBrush Value) { }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        protected virtual System.Type EqualityContract { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public TBrush Value { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Deconstruct(out TBrush Value) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override bool Equals(object? obj) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public virtual bool Equals(WpfMath.Rendering.GenericBrush<TBrush>? other) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override int GetHashCode() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator ==(WpfMath.Rendering.GenericBrush<TBrush>? left, WpfMath.Rendering.GenericBrush<TBrush>? right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator !=(WpfMath.Rendering.GenericBrush<TBrush>? left, WpfMath.Rendering.GenericBrush<TBrush>? right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        protected virtual bool PrintMembers(System.Text.StringBuilder builder) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override string ToString() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public virtual WpfMath.Rendering.GenericBrush<TBrush> <Clone>$() { throw null; }
    }
    public partial interface IBrush
    {
    }
    public partial interface IBrushFactory
    {
        WpfMath.Rendering.IBrush FromColor(WpfMath.Colors.RgbaColor color);
    }
    public partial interface IElementRenderer
    {
        void FinishRendering();
        void RenderCharacter(WpfMath.CharInfo info, double x, double y, WpfMath.Rendering.IBrush? foreground);
        void RenderElement(WpfMath.Boxes.Box box, double x, double y);
        void RenderRectangle(WpfMath.Rendering.Rectangle rectangle, WpfMath.Rendering.IBrush? foreground);
        void RenderTransformed(WpfMath.Boxes.Box box, System.Collections.Generic.IEnumerable<WpfMath.Rendering.Transformations.Transformation> transforms, double x, double y);
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct Point : System.IEquatable<WpfMath.Rendering.Point>
    {
        private object _dummy;
        private int _dummyPrimitive;
        public Point(double X, double Y) { throw null; }
        public double X { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Y { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Deconstruct(out double X, out double Y) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override bool Equals(object obj) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public bool Equals(WpfMath.Rendering.Point other) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override int GetHashCode() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator ==(WpfMath.Rendering.Point left, WpfMath.Rendering.Point right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator !=(WpfMath.Rendering.Point left, WpfMath.Rendering.Point right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override string ToString() { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct Rectangle : System.IEquatable<WpfMath.Rendering.Rectangle>
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public Rectangle(double x, double y, double width, double height) { throw null; }
        public Rectangle(WpfMath.Rendering.Point TopLeft, WpfMath.Rendering.Size Size) { throw null; }
        public double Height { get { throw null; } }
        public WpfMath.Rendering.Size Size { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public WpfMath.Rendering.Point TopLeft { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Width { get { throw null; } }
        public double X { get { throw null; } }
        public double Y { get { throw null; } }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Deconstruct(out WpfMath.Rendering.Point TopLeft, out WpfMath.Rendering.Size Size) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override bool Equals(object obj) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public bool Equals(WpfMath.Rendering.Rectangle other) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override int GetHashCode() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator ==(WpfMath.Rendering.Rectangle left, WpfMath.Rendering.Rectangle right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator !=(WpfMath.Rendering.Rectangle left, WpfMath.Rendering.Rectangle right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override string ToString() { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct Size : System.IEquatable<WpfMath.Rendering.Size>
    {
        private object _dummy;
        private int _dummyPrimitive;
        public Size(double Width, double Height) { throw null; }
        public double Height { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public double Width { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public void Deconstruct(out double Width, out double Height) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override bool Equals(object obj) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public bool Equals(WpfMath.Rendering.Size other) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override int GetHashCode() { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator ==(WpfMath.Rendering.Size left, WpfMath.Rendering.Size right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public static bool operator !=(WpfMath.Rendering.Size left, WpfMath.Rendering.Size right) { throw null; }
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public override string ToString() { throw null; }
    }
    public static partial class TeXFormulaExtensions
    {
        public static void RenderTo(this WpfMath.TexFormula formula, WpfMath.Rendering.IElementRenderer renderer, WpfMath.TexEnvironment environment, double x, double y) { }
    }
}
namespace WpfMath.Rendering.Transformations
{
    public abstract partial class Transformation
    {
        internal Transformation() { }
        public abstract WpfMath.Rendering.Transformations.TransformationKind Kind { get; }
        public abstract WpfMath.Rendering.Transformations.Transformation Scale(double scale);
        public partial class Rotate : WpfMath.Rendering.Transformations.Transformation
        {
            public Rotate(double rotationDegrees) { }
            public override WpfMath.Rendering.Transformations.TransformationKind Kind { get { throw null; } }
            public double RotationDegrees { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
            public override WpfMath.Rendering.Transformations.Transformation Scale(double scale) { throw null; }
        }
        public partial class Translate : WpfMath.Rendering.Transformations.Transformation
        {
            public Translate(double x, double y) { }
            public override WpfMath.Rendering.Transformations.TransformationKind Kind { get { throw null; } }
            public double X { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
            public double Y { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
            public override WpfMath.Rendering.Transformations.Transformation Scale(double scale) { throw null; }
        }
    }
    public enum TransformationKind
    {
        Translate = 0,
        Rotate = 1,
    }
}
namespace WpfMath.Utils
{
    public static partial class Result
    {
        public static WpfMath.Utils.Result<TValue> Error<TValue>(System.Exception error) { throw null; }
        public static WpfMath.Utils.Result<TValue> Ok<TValue>(TValue value) { throw null; }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly partial struct Result<TValue>
    {
        private readonly TValue value;
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public Result(TValue value, System.Exception? error) { throw null; }
        public System.Exception? Error { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public bool IsSuccess { get { throw null; } }
        public TValue Value { get { throw null; } }
        public WpfMath.Utils.Result<TProduct> Map<TProduct>(System.Func<TValue, TProduct> mapper) { throw null; }
    }
}
