//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AvaloniaMath.Controls
{
    public partial class FormulaBlock : Avalonia.Controls.Control
    {
        public static readonly Avalonia.StyledProperty<System.Collections.ObjectModel.ObservableCollection<System.Exception>> ErrorsProperty;
        public static readonly Avalonia.StyledProperty<Avalonia.Markup.Xaml.Templates.ControlTemplate> ErrorTemplateProperty;
        public static readonly Avalonia.StyledProperty<string> FormulaProperty;
        public static readonly Avalonia.StyledProperty<bool> HasErrorProperty;
        public static readonly Avalonia.StyledProperty<double> ScaleProperty;
        public static readonly Avalonia.StyledProperty<string> SystemTextFontNameProperty;
        public FormulaBlock() { }
        public System.Collections.ObjectModel.ObservableCollection<System.Exception> Errors { get { throw null; } }
        public Avalonia.Markup.Xaml.Templates.ControlTemplate ErrorTemplate { get { throw null; } set { } }
        public string Formula { get { throw null; } set { } }
        public bool HasError { get { throw null; } }
        public double Scale { get { throw null; } set { } }
        public string SystemTextFontName { get { throw null; } set { } }
        protected void InvalidateFormattedText() { }
        protected override Avalonia.Size MeasureOverride(Avalonia.Size availableSize) { throw null; }
        public override void Render(Avalonia.Media.DrawingContext context) { }
    }
}
namespace AvaloniaMath.Fonts
{
    public partial class AvaloniaMathFontProvider : WpfMath.Fonts.IFontProvider
    {
        internal AvaloniaMathFontProvider() { }
        public static AvaloniaMath.Fonts.AvaloniaMathFontProvider Instance;
        public WpfMath.Fonts.IFontTypeface ReadFontFile(string fontFileName) { throw null; }
    }
}
namespace AvaloniaMath.Parsers
{
    public static partial class AvaloniaTeXFormulaParser
    {
        public static WpfMath.TexFormulaParser Instance { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
    }
}
namespace AvaloniaMath.Rendering
{
    public static partial class AvaloniaBrushExtensions
    {
        public static Avalonia.Media.IBrush? ToAvalonia(this WpfMath.Rendering.IBrush? brush) { throw null; }
        public static WpfMath.Rendering.IBrush? ToPlatform(this Avalonia.Media.Brush? brush) { throw null; }
    }
    public partial class AvaloniaBrushFactory : WpfMath.Rendering.IBrushFactory
    {
        internal AvaloniaBrushFactory() { }
        public static AvaloniaMath.Rendering.AvaloniaBrushFactory Instance { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
        public WpfMath.Rendering.IBrush FromColor(WpfMath.Colors.RgbaColor color) { throw null; }
    }
    public static partial class AvaloniaTeXEnvironment
    {
        public static WpfMath.TexEnvironment Create(WpfMath.TexStyle style = 0, double scale = 20, string systemTextFontName = "Arial", Avalonia.Media.Brush? foreground = null, Avalonia.Media.Brush? background = null) { throw null; }
    }
    public partial class GeometryElementRenderer : WpfMath.Rendering.IElementRenderer
    {
        public GeometryElementRenderer(WpfMath.Rendering.GeometryGroup geometry, double scale) { }
        public void FinishRendering() { }
        public void RenderCharacter(WpfMath.CharInfo info, double x, double y, WpfMath.Rendering.IBrush? foreground) { }
        public void RenderElement(WpfMath.Boxes.Box box, double x, double y) { }
        public void RenderRectangle(WpfMath.Rendering.Rectangle rectangle, WpfMath.Rendering.IBrush? foreground) { }
        public void RenderTransformed(WpfMath.Boxes.Box box, System.Collections.Generic.IEnumerable<WpfMath.Rendering.Transformations.Transformation> transforms, double x, double y) { }
    }
}
namespace WpfMath.Rendering
{
    public partial class GeometryGroup : Avalonia.Media.Geometry
    {
        public GeometryGroup() { }
        public System.Collections.Generic.IList<Avalonia.Media.Geometry> Children { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public override Avalonia.Media.Geometry Clone() { throw null; }
        protected override Avalonia.Platform.IGeometryImpl CreateDefiningGeometry() { throw null; }
    }
}
